### ISSUE TITLE
Errors while running

### ISSUE THREAD

**Issue by mohuk** [hungrilla/potato#5]
Potato is showing some errors when I run it. 
![screen shot 2015-07-04 at 5 49 02 am](https://cloud.githubusercontent.com/assets/3163551/8505885/f1b93416-2210-11e5-8d3c-34780b983680.png)

**Comment by umayr** [comment]
This happens in a number of situations. The most common ones I run into are:
- The server crashed.
- The server refused your connection, most likely blocked by User-Agent.

When you, as a client, send a request to a remote server, and receive no timely response. Your socket is ended which thrown this error. We should catch this error and decide how to handle it; whether retry the request, queue it for later, etc.

I can't reproduce it, somehow. 
![Image](http://i.imgur.com/LNORQUN.png)

May be I need to flush my database first?
